import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        AudioContext: 'readonly',
        OscillatorNode: 'readonly',
        GainNode: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        getComputedStyle: 'readonly',
        AbortController: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        indexedDB: 'readonly',
        structuredClone: 'readonly',
        queueMicrotask: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        // Service Worker globals
        self: 'readonly',
        caches: 'readonly',
        clients: 'readonly',
        registration: 'readonly',
        skipWaiting: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        ServiceWorkerGlobalScope: 'readonly',
        // Node/CommonJS (for config files)
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        // Project cross-file globals (shared via <script> tags)
        state: 'writable',
        APP_VERSION: 'readonly',
        MetaStore: 'readonly', // U5 device-preference key/value store (js/state.js)
        FACTION_REGISTRY: 'readonly',
        FACTION_REGISTRY_FO3: 'readonly',
        SKILL_KEYS: 'readonly',
        SKILL_KEYS_FO3: 'readonly',
        GAME_DEFS: 'readonly',
        THEMES: 'readonly',
        _activeDef: 'readonly',
        getFactionRegistry: 'readonly',
        getSkillKeys: 'readonly',
        RobcoEvents: 'readonly', // U7 OS event bus (js/state.js)
        _logEvent: 'readonly', // P4 Terminal Record structured-event writer (js/state.js)
        _migrateEventLog: 'readonly', // P4 [T#]→eventLog migration helper (js/state.js)
        switchTab: 'readonly',
        initTabs: 'readonly',
        appendToChat: 'readonly',
        loadUI: 'readonly',
        saveState: 'readonly',
        migrateState: 'readonly',
        autoImportState: 'readonly',
        sanitizeImportedContainer: 'readonly',
        syncStateFromDom: 'readonly',
        recordLocationVisit: 'readonly',
        generateSyncPayload: 'readonly',
        restoreChatHistory: 'readonly',
        chatHistory: 'writable',
        transmitMessage: 'readonly',
        _wireApiEventBusSubscribers: 'readonly', // U7 OS event bus (api.js)
        fetchAuthorizedModels: 'readonly',
        lookupItemInDb: 'readonly',
        lookupWeaponStats: 'readonly',
        lookupBestiaryEntry: 'readonly',
        getBestiaryNames: 'readonly', // content-aware quick-log autocomplete source (js/db_nv.js / js/db_fo3.js)
        getChemsTable: 'readonly',
        getQuestItemDetail: 'readonly', // U9-4 CONSULT reserved-column surfacing (js/db_nv.js or js/db_fo3.js)
        renderThreat: 'readonly',
        renderConsult: 'readonly',
        renderDatabankPanel: 'readonly',
        renderBioScan: 'readonly',
        _nativePadBind: 'readonly', // Tool Deck + Quick-Draw Holster (ui-core.js), called from _routeNativeCommand (api.js)
        _nativePadFire: 'readonly', // Tool Deck + Quick-Draw Holster (ui-core.js), called from _routeNativeCommand (api.js)
        _openSysModal: 'readonly',
        openModal: 'readonly', // Step 2 Phase 0 U12 consolidated modal driver (ui-core.js)
        confirmAction: 'readonly', // Step 2 Phase 0 U12 diegetic confirm() replacement (ui-core.js)
        _vatsIsMelee: 'readonly',
        getGameContext: 'readonly',
        getIdentity: 'readonly', // DO-K identity keystone accessor (js/state.js)
        // P8 Global Immersion dial — gate helpers + pref live in state.js, the UI in ui-core.js
        getImmersionTier: 'readonly',
        immersionAllows: 'readonly',
        setImmersionTier: 'readonly',
        // Step 2 Phase 2 B1 — Command-Line MODE: device-pref accessors (js/state.js),
        // quick-log autocomplete source (js/api.js), quick-log setter reuse (js/ui-render.js)
        getInputMode: 'readonly',
        setInputMode: 'readonly',
        otherInputMode: 'readonly',
        _commandSuggestions: 'readonly',
        _hideModeHint: 'readonly',
        _resolveCommandInput: 'readonly',
        // Small-UI-polish batch — composer auto-grow (js/ui-core.js), called from js/api.js
        // after clearing #chatInput so the box resets to its small size after every send
        _autoGrowComposer: 'readonly',
        markLocationVisited: 'readonly',
        // Step 2 Phase 2 A1 — Ambient Runtime (js/runtime.js): lifecycle state machine + observer scheduler
        AmbientRuntime: 'readonly',
        initAmbientRuntime: 'readonly',
        initTestConsole: 'readonly', // staging/dev-only Test Console (js/test-console.js)
        getAmmoCalibers: 'readonly',
        getVendors: 'readonly',
        getTradeCatalog: 'readonly',
        renderTrade: 'readonly',
        renderTradeBuyList: 'readonly',
        renderTradeSellList: 'readonly',
        setTradeVendor: 'readonly',
        doBuy: 'readonly',
        doSell: 'readonly',
        renderLoot: 'readonly',
        renderLootList: 'readonly',
        renderHolster: 'readonly', // Tool Deck + Quick-Draw Holster (ui-render.js), called from ui-core.js
        _deckTargetSuggestions: 'readonly', // Tool Deck #deckTarget autocomplete source (ui-render.js), wired from ui-saves.js
        doLoot: 'readonly',
        _lootAdd: 'readonly',
        expandPanelForCategory: 'readonly',
        closeModal: 'readonly',
        playSyncTone: 'readonly',
        playClack: 'readonly',
        playPanelClick: 'readonly',
        playLevelUpJingle: 'readonly',
        playChipClick: 'readonly', // B2c Module Bay hardware SFX (ui-audio.js)
        playBoardThunk: 'readonly', // B2c Module Bay hardware SFX (ui-audio.js)
        toggleAudio: 'readonly', // ui-audio.js channel-mute setter (ui-core.js calls it via _schemSetHardwareSfx)
        triggerHaptic: 'readonly', // WU-F2 Haptic Solenoid (ui-audio.js)
        initHaptic: 'readonly', // WU-F2 Haptic Solenoid (ui-audio.js)
        initRadio: 'readonly', // WU-F5 Pip-Boy Radio (ui-audio.js)
        _wireAudioEventBusSubscribers: 'readonly', // U7 OS event bus (ui-audio.js)
        startHeartbeat: 'readonly',
        stopHeartbeat: 'readonly',
        playBootDrone: 'readonly',
        startThermalLoad: 'readonly',
        stopThermalLoad: 'readonly',
        // Account module cross-file globals (js/ui-account.js ↔ js/ui.js)
        renderAccount: 'readonly',
        renderSavesList: 'readonly',
        listLocalSaves: 'readonly',
        undoLastSync: 'readonly',
        // Saves module cross-file globals (js/ui-saves.js ↔ js/ui.js)
        CHAT_MAX: 'readonly',
        _chatSaveTimer: 'writable',
        initRegistryAutocomplete: 'readonly',
        restoreRollingBackup: 'readonly',
        // Render module cross-file globals (js/ui-render.js ↔ js/ui.js)
        _invFilter: 'writable',
        _updatePanelBadges: 'readonly',
        escapeHtml: 'readonly',
        emptyState: 'readonly',
        escapeAndFormat: 'readonly',
        getTypewriterSpeed: 'readonly',
        renderInventory: 'readonly',
        renderSquad: 'readonly',
        renderStatus: 'readonly',
        renderCampaignNotes: 'readonly',
        renderFactionRep: 'readonly',
        renderPerks: 'readonly',
        renderQuests: 'readonly',
        renderSessionStats: 'readonly',
        renderEquipped: 'readonly',
        renderCampaignStatus: 'readonly',
        // Audio module cross-file globals (js/ui-audio.js ↔ js/ui.js)
        AudioSettings: 'readonly',
        audioCtx: 'writable',
        _geigerCurrentRate: 'writable',
        geigerRunning: 'writable',
        geigerTimeout: 'writable',
        crtHumGain: 'writable',
        changeOpticsColor: 'readonly',
        _applyThemeVars: 'readonly',
        _resolveDefaultOptics: 'readonly',
        _opticStorageKey: 'readonly',
        _resolveOptic: 'readonly',
        _updateOpticsDefaultLabel: 'readonly',
        // WU-optics-picker: GREEN FAMILY cartridge cross-file globals
        OPTIC_FAMILY_LABELS: 'readonly',
        _themeFamilyMembers: 'readonly',
        _resolveOpticsFamilyRepresentative: 'readonly',
        _updateOpticsFamilyRepresentative: 'readonly',
        _expandOpticsFamily: 'readonly',
        _collapseOpticsFamily: 'readonly',
        // Module Bay (Step 2 · Phase 2 · B2a) cross-file globals
        isHighLumenEnabled: 'readonly',
        isHapticEnabled: 'readonly',
        isWakeLockEnabled: 'readonly',
        _seatOpticsTube: 'readonly',
        _updateOpticsBoardStatus: 'readonly',
        _updateSonicBoardStatus: 'readonly',
        _updateUplinkBoardStatus: 'readonly',
        renderModuleBay: 'readonly',
        initModuleBay: 'readonly',
        releaseBayHatch: 'readonly',
        toggleBaySchematic: 'readonly',
        renderBaySchematic: 'readonly',
        _schemSetGeminiSync: 'readonly',
        _logBaySvc: 'readonly',
        exportCampaignLog: 'readonly',
        _svcExportCampaignLog: 'readonly',
        _svcViewChangelog: 'readonly',
        _svcInstallPwa: 'readonly',
        playHeadCrippleSound: 'readonly',
        playLimbCrippleSound: 'readonly',
        playLimbRestoreSound: 'readonly',
        playWakeTone: 'readonly',
        setCrtHumIntensity: 'readonly',
        setGeigerRate: 'readonly',
        startCrtHum: 'readonly',
        stopCrtHum: 'readonly',
        startTinnitus: 'readonly',
        stopTinnitus: 'readonly',
        runBootSequence: 'readonly',
        triggerPhosphorGhost: 'readonly',
        calendarToTicks: 'readonly',
        setupXpBarInteraction: 'readonly',
        onLvlInputChanged: 'readonly',
        onTimeInputChanged: 'readonly',
        renderKarmaCenter: 'readonly',
        _updateContextPanels: 'readonly',
        renderWorldMap: 'readonly',
        showVATSOverlay: 'readonly',
        showHelpModal: 'readonly',
        showErrorLog: 'readonly',
        updateMath: 'readonly',
        wipeTerminal: 'readonly',
        _fmtOverseerDuration: 'readonly', // WU-F7 duration formatter, reused by U9-2 CURRENT SITTING (js/ui-core.js)
        attachedImageData: 'writable',
        attachedImageMimeType: 'writable',
        _buildFactions: 'readonly',
        _saveTimer: 'writable',
        renderAmmo: 'readonly',
        addAmmo: 'readonly',
        removeAmmo: 'readonly',
        initAmmoDatalist: 'readonly',
        initLocationDatalist: 'readonly',
        // Fallout Data Registry (js/reg_nv.js or js/reg_fo3.js)
        FALLOUT_REGISTRY: 'readonly',
        SKILL_LABELS: 'readonly',
        registrySearch: 'readonly',
        renderCollectibles: 'readonly',
        renderLincolnMemorabilia: 'readonly',
        toggleLincolnItem: 'readonly',
        setLincolnDisposition: 'readonly',
        renderTraits: 'readonly',
        toggleTrait: 'readonly',
        renderSkillBooks: 'readonly',
        toggleSkillBook: 'readonly',
        renderMagazines: 'readonly',
        toggleMagazine: 'readonly',
        renderCraft: 'readonly',
        setCraftFilter: 'readonly',
        craftSetMax: 'readonly',
        doCraft: 'readonly',
        doScrap: 'readonly',
        _craftGetHave: 'readonly',
        // Time system (js/ui.js)
        formatGameTime: 'readonly',
        _resolveGameDateTime: 'readonly',
        getGameDate: 'readonly',
        renderGameDate: 'readonly',
        // Faction reputation editing (js/ui.js)
        adjustFaction: 'readonly',
        // Location field change handler (js/ui.js)
        onLocationChange: 'readonly',
        // Map view toggle handler (js/ui.js)
        setMapView: 'readonly',
        // Game database CSVs (js/db_nv.js or js/db_fo3.js)
        databaseCSVs: 'readonly',
      },
    },
    rules: {
      // Catch real bugs
      'no-undef': 'error',
      'no-redeclare': 'off', // Cross-file globals are declared in config AND defined in source
      'no-unused-vars': [
        'warn',
        {
          vars: 'local', // top-level declarations are cross-file global API — only check local scope
          argsIgnorePattern: '^_|^e$|^err$',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_$|^e$|^err$', // catch (e) / catch (_) patterns
        },
      ],
      'no-constant-condition': 'warn',
      'no-debugger': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-unreachable': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // Permissive on style — Prettier handles formatting
      'no-extra-semi': 'off',
      semi: 'off',
      quotes: 'off',
      indent: 'off',
      'comma-dangle': 'off',
    },
  },
  // cloud.js uses ES module syntax (import/export)
  {
    files: ['js/cloud.js'],
    languageOptions: {
      sourceType: 'module',
      globals: {
        // api.js globals consumed by the ES module
        sanitizeImportedContainer: 'readonly',
        autoImportState: 'readonly',
        restoreChatHistory: 'readonly',
        playSyncTone: 'readonly',
        state: 'writable',
        APP_VERSION: 'readonly',
        // ui-core.js globals (Step 2 Phase 0 U12 modal driver)
        openModal: 'readonly',
        confirmAction: 'readonly',
      },
    },
  },
  {
    ignores: [
      'node_modules/',
      'dist/',
      'dist-staging/',
      '_site/',
      '*.min.js',
      'eslint.config.mjs',
      'tests/render-check.mjs',
      'tests/boot-smoke.mjs',
      'tests/a11y-check.mjs',
      'tests/test-html-check.mjs',
      'tests/browser-server.mjs',
      'tests/browser-shared.mjs',
      'tests/_diag*.mjs',
      'scripts/cf-staging-build.mjs',
    ],
  },
];
