import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        AudioContext: 'readonly',
        OscillatorNode: 'readonly',
        GainNode: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        AbortController: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        indexedDB: 'readonly',
        structuredClone: 'readonly',
        queueMicrotask: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        // Service Worker globals
        self: 'readonly',
        caches: 'readonly',
        clients: 'readonly',
        registration: 'readonly',
        skipWaiting: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        ServiceWorkerGlobalScope: 'readonly',
        // Node/CommonJS (for config files)
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        // Project cross-file globals (shared via <script> tags)
        state: 'writable',
        APP_VERSION: 'readonly',
        FACTION_REGISTRY: 'readonly',
        FACTION_REGISTRY_FO3: 'readonly',
        SKILL_KEYS: 'readonly',
        SKILL_KEYS_FO3: 'readonly',
        GAME_DEFS: 'readonly',
        _activeDef: 'readonly',
        getFactionRegistry: 'readonly',
        getSkillKeys: 'readonly',
        switchTab: 'readonly',
        initTabs: 'readonly',
        appendToChat: 'readonly',
        loadUI: 'readonly',
        saveState: 'readonly',
        migrateState: 'readonly',
        autoImportState: 'readonly',
        sanitizeImportedContainer: 'readonly',
        syncStateFromDom: 'readonly',
        generateSyncPayload: 'readonly',
        restoreChatHistory: 'readonly',
        chatHistory: 'writable',
        transmitMessage: 'readonly',
        fetchAuthorizedModels: 'readonly',
        lookupItemInDb: 'readonly',
        getAmmoCalibers: 'readonly',
        gameTimeToTicks: 'readonly',
        expandPanelForCategory: 'readonly',
        closeModal: 'readonly',
        tradeItem: 'readonly',
        playSyncTone: 'readonly',
        playClack: 'readonly',
        playPanelClick: 'readonly',
        playLevelUpJingle: 'readonly',
        startHeartbeat: 'readonly',
        stopHeartbeat: 'readonly',
        playBootDrone: 'readonly',
        startThermalLoad: 'readonly',
        stopThermalLoad: 'readonly',
        // Account module cross-file globals (js/ui-account.js ↔ js/ui.js)
        renderAccount: 'readonly',
        renderSavesList: 'readonly',
        listLocalSaves: 'readonly',
        undoLastSync: 'readonly',
        // Saves module cross-file globals (js/ui-saves.js ↔ js/ui.js)
        CHAT_MAX: 'readonly',
        _chatSaveTimer: 'writable',
        initRegistryAutocomplete: 'readonly',
        restoreRollingBackup: 'readonly',
        // Render module cross-file globals (js/ui-render.js ↔ js/ui.js)
        _invFilter: 'writable',
        _updatePanelBadges: 'readonly',
        escapeHtml: 'readonly',
        emptyState: 'readonly',
        escapeAndFormat: 'readonly',
        getTypewriterSpeed: 'readonly',
        renderInventory: 'readonly',
        renderSquad: 'readonly',
        renderStatus: 'readonly',
        renderCampaignNotes: 'readonly',
        renderFactionRep: 'readonly',
        renderPerks: 'readonly',
        renderQuests: 'readonly',
        renderSessionStats: 'readonly',
        renderEquipped: 'readonly',
        renderCampaignStatus: 'readonly',
        // Audio module cross-file globals (js/ui-audio.js ↔ js/ui.js)
        AudioSettings: 'readonly',
        audioCtx: 'writable',
        _geigerCurrentRate: 'writable',
        geigerRunning: 'writable',
        geigerTimeout: 'writable',
        crtHumGain: 'writable',
        changeOpticsColor: 'readonly',
        playHeadCrippleSound: 'readonly',
        playLimbCrippleSound: 'readonly',
        playLimbRestoreSound: 'readonly',
        playWakeTone: 'readonly',
        setCrtHumIntensity: 'readonly',
        setGeigerRate: 'readonly',
        startCrtHum: 'readonly',
        startTinnitus: 'readonly',
        stopTinnitus: 'readonly',
        runBootSequence: 'readonly',
        triggerPhosphorGhost: 'readonly',
        calendarToTicks: 'readonly',
        setupXpBarInteraction: 'readonly',
        onLvlInputChanged: 'readonly',
        onTimeInputChanged: 'readonly',
        renderKarmaCenter: 'readonly',
        _updateContextPanels: 'readonly',
        renderWorldMap: 'readonly',
        showVATSOverlay: 'readonly',
        showHelpModal: 'readonly',
        showErrorLog: 'readonly',
        updateMath: 'readonly',
        wipeTerminal: 'readonly',
        attachedImageData: 'writable',
        attachedImageMimeType: 'writable',
        _buildFactions: 'readonly',
        _saveTimer: 'writable',
        renderAmmo: 'readonly',
        addAmmo: 'readonly',
        removeAmmo: 'readonly',
        initAmmoDatalist: 'readonly',
        initLocationDatalist: 'readonly',
        // Fallout Data Registry (js/reg_nv.js or js/reg_fo3.js)
        FALLOUT_REGISTRY: 'readonly',
        SKILL_LABELS: 'readonly',
        registrySearch: 'readonly',
        renderCollectibles: 'readonly',
        renderLincolnMemorabilia: 'readonly',
        toggleLincolnItem: 'readonly',
        setLincolnDisposition: 'readonly',
        renderTraits: 'readonly',
        toggleTrait: 'readonly',
        renderCraft: 'readonly',
        setCraftFilter: 'readonly',
        craftSetMax: 'readonly',
        doCraft: 'readonly',
        doScrap: 'readonly',
        _craftGetHave: 'readonly',
        // Time system (js/ui.js)
        formatGameTime: 'readonly',
        ticksToGameTime: 'readonly',
        _resolveGameDateTime: 'readonly',
        getGameDate: 'readonly',
        renderGameDate: 'readonly',
        // Faction reputation editing (js/ui.js)
        adjustFaction: 'readonly',
        // Location field change handler (js/ui.js)
        onLocationChange: 'readonly',
        // Map view toggle handler (js/ui.js)
        setMapView: 'readonly',
        // Game database CSVs (js/db_nv.js or js/db_fo3.js)
        databaseCSVs: 'readonly',
      },
    },
    rules: {
      // Catch real bugs
      'no-undef': 'error',
      'no-redeclare': 'off', // Cross-file globals are declared in config AND defined in source
      'no-unused-vars': [
        'warn',
        {
          vars: 'local', // top-level declarations are cross-file global API — only check local scope
          argsIgnorePattern: '^_|^e$|^err$',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_$|^e$|^err$', // catch (e) / catch (_) patterns
        },
      ],
      'no-constant-condition': 'warn',
      'no-debugger': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-unreachable': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // Permissive on style — Prettier handles formatting
      'no-extra-semi': 'off',
      semi: 'off',
      quotes: 'off',
      indent: 'off',
      'comma-dangle': 'off',
    },
  },
  // cloud.js uses ES module syntax (import/export)
  {
    files: ['js/cloud.js'],
    languageOptions: {
      sourceType: 'module',
      globals: {
        // api.js globals consumed by the ES module
        sanitizeImportedContainer: 'readonly',
        autoImportState: 'readonly',
        restoreChatHistory: 'readonly',
        playSyncTone: 'readonly',
        state: 'writable',
        APP_VERSION: 'readonly',
      },
    },
  },
  {
    ignores: [
      'node_modules/',
      'dist/',
      '*.min.js',
      'eslint.config.mjs',
      'tests/render-check.mjs',
      'tests/boot-smoke.mjs',
      'tests/a11y-check.mjs',
      'tests/_diag*.mjs',
    ],
  },
];
